# Generated by Django 3.1.2 on 2020-11-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201101_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(null=True, upload_to='images/city_pics/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/post_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/profile_pics/profile_placeholder.jpg', upload_to='images/profile_pics/'),
        ),
    ]
