# Generated by Django 3.1.2 on 2020-11-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_post_city'),
        ('main_app', '0006_auto_20201102_0737'),
    ]

    operations = [
    ]
