# Generated by Django 3.1.2 on 2020-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
