# Generated by Django 3.1.2 on 2020-11-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_city_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
